apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: back-end-outbound
spec:
  podSelector:
    matchLabels:
      tier: back-end
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 10.0.0.100/32
    ports:
    - protocol: TCP
      port: 3306