apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-backend
spec:
  podSelector:
    matchLabels:
      app: foo
  policyTypes:
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 34.65.54.160/32
    ports:
    - protocol: TCP
      port: 80