apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    tier: front-end
    app: foo
  name: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foo
        tier: front-end
    spec:
      containers:
      - name: nginx
        image: "gcr.io/google-samples/hello-app:2.0"
        env:
        - name: "PORT"
          value: "80"
status: {}